### PR TITLE
Fixed TS0207 

### PR DESCRIPTION
**Pull request by 9Mad-Max5**
Commented out the Blitzwolf TS0207 and replaced it by the correct TuYa TS0207 with an added picture.

### CODE REVIEW

**Comment by arteck** [comment]
TS0207 its a  Water leak detector

**Comment by 9Mad-Max5** [comment]
> TS0207 its a Water leak detector

Are we sure about that ts0207 is a leakage sensor?
Is there anything why this repeater could be self identified wrong?

**Comment by arteck** [comment]
https://github.com/Koenkk/zigbee-herdsman-converters/issues/1540

**Comment by arteck** [comment]
it works now

**Comment by 9Mad-Max5** [comment]
mhm ok can you tell me where the changes happend?

**Pull request closed without merging**
