### PR TITLE
Hue sml sensitivity

### PR DESCRIPTION
**Pull request by allofmex**
Depends on https://github.com/Koenkk/zigbee-shepherd-converters/pull/484
Feature requested in https://github.com/ioBroker/ioBroker.zigbee/issues/312

### CODE REVIEW

**Comment by kirovilya** [comment]
will merge?

**Comment by allofmex** [comment]
No. Koenkk changed something. Have to adjust first

**Comment by kirovilya** [comment]
new converters require a little fix code - send **options** object to converter
https://github.com/Koenkk/zigbee-shepherd-converters/commit/744423da9d24e60a1105044702b951b2a2fdeff3
https://github.com/Koenkk/zigbee2mqtt/commit/ef013467766d970d0eead977e90347abb834ef63

**Comment by allofmex** [comment]
> new converters require a little fix code

Sorry. Did not noticed this change. Was wondering why the change version 9 -> 10 but didn't got it.

**Pull request merged**
