### PR TITLE
Added new states for "AC0251100NJ/AC0251600NJ/AC0251700NJ" (Osram switch mini)

### PR DESCRIPTION
**Pull request by obakuhl**
Added new states for "AC0251100NJ/AC0251600NJ/AC0251700NJ" (Osram switch mini). This was necessary so that the boolean values are also written in the corresponding objects. The background is that after the last adjustment the values of the objects circle_click, circle_ hold, down, down_hold, up and up_hold were not updated: [Forum entry](https://forum.iobroker.net/topic/21381/gel%C3%B6st-osram-smart-mini-switch/48)

### CODE REVIEW

**Comment by asgothian** [comment]
Please verify: 
- How does the Objects of the Osram switch change if the device is added to the exclude ("Ausschliessen") List.
- Is full functionality for the device provided in this case ?

Note that the explicit definition of states and devices in the zigbee Adapter is deprecated and the long term plan is to remove as many of the explicit Device definitions as possible in order to limit the amount of code needed for the zigbee adapter.

The above mentioned issue with states getting disconnected is a direct result of having explicitly defined devices and states within the adapter rather than relying on the exposes provided by the zigbee-herdsman-converters library.

A.

**Comment by asgothian** [comment]
Did you run the state cleanup to remove all the states which are no longer connected to a converter ?

**Comment by obakuhl** [comment]
No I haven't yet, but before I do that, what are the consequences? Do you expect that the objects "state", "circle", "hold" and "release" will be deleted?

**Comment by arteck** [comment]
i think we can close here

**Comment by obakuhl** [comment]
We can close it when the problem/topic is solved. Is that the case? I am not sure about that.

**Comment by arteck** [comment]
this issue is 6 month old.. and we are at least 15 versions ahead
what is wrong ? 
i have also the button here and cant find any problems

**Comment by obakuhl** [comment]
The problem is or was that boolean objects were added and the old ones stopped working. I changed that with another PR, but then the new (boolean) ones didn't work anymore. With this PR I wanted to introduce a solution where both ways work, asgothian wanted to solve the problem in a different way. This is the current state.

**Comment by arteck** [comment]
here is solved https://forum.iobroker.net/topic/21381/gel%C3%B6st-osram-smart-mini-switch/53

**Pull request closed without merging**
