### PR TITLE
Add support for new Philips Hue models

### PR DESCRIPTION
**Pull request by agross**
Related PRs in herdsman-converters:

https://github.com/Koenkk/zigbee-herdsman-converters/pull/3163
https://github.com/Koenkk/zigbee-herdsman-converters/pull/3165
https://github.com/Koenkk/zigbee-herdsman-converters/pull/3175

### CODE REVIEW

**Comment by agross** [comment]
Aha, so since the last time I contributed here that appears to have
changed. Now the basic idea is to convert all devices to use exposes and no
longer having to add new devices in herdsman-converters and here. Did I
understand that correctly?

**Comment by kirovilya** [comment]
not entirely correct. devices in iob.zigbee are created automatically based on the exposes described in the zigbee-herdsman-converters. therefore, you need to add new devices only to zigbee-herdsman-converters (without adding them to iobroker.zigbee)

**Comment by agross** [comment]
I think that is basically what I said.

I tried to verify that loading images from zigbee2mqtt.io works with one of my devices that z2m supports.

1. Without anything "to exclude", the [PTM215Z switch](https://www.zigbee2mqtt.io/devices/PTM_215Z.html) looks like this:
    
1. After excluding it from iobroker.zigbee and restarting the instance it still looks the same
1. The cards on the "to exclude" tab look way too big.
    
1. The link to the device under "to exclude" points to a non-existing URL
    `https://www.zigbee2mqtt.io/devices/PTM%20215Z.html`
    The space should have been replaced by an underscore (see link in 1).
1. The image from zigbee2mqtt.io does not show up anywhere.

This is the device JSON from ioBroker's objects:

```json
{
  "type": "device",
  "common": {
    "name": "PTM 215Z",
    "type": "PTM 215Z"
  },
  "native": {
    "id": "000000000172c7db"
  },
  "from": "system.adapter.zigbee.0",
  "user": "system.user.admin",
  "ts": 1634326069980,
  "_id": "zigbee.0.000000000172c7db",
  "acl": {
    "object": 1636,
    "owner": "system.user.agross",
    "ownerGroup": "system.group.administrator"
  }
}
```

**Comment by kirovilya** [comment]
yes, this is a bug

**Comment by agross** [comment]
That fixes images, but not the card size and the model URL. For model URLs it seems you need to replace whitespace with an underscore.

**Pull request closed without merging**
