### PR TITLE
Admin changes

### PR DESCRIPTION
**Pull request by asgothian**
Changes to admin panel:

show coordinator in device list
image for coordinator in network map
show configure status in device list
configure on message, active for 5 minutes after adapter start, 1 minute after button press
show available status of coordinators on device list

### CODE REVIEW

**Comment by allofmex** [comment]
@asgothian How stable is your network, using this changes? Especially hue dimmer switch (rwl021) and hue motion sensor (sml001)? 
Without your changes, I'm still having the problem that dimmer switch stops working after some hours. Motion sensor runs better, but still not 100%. Anything that helps would be welcome. :-)

Other question? Should we really maintain another `aliveStates` list? One in object states and now a second in admin interface??

PS: your code needs some cleanup (function names should start lowercase, '{' should be same line as function..., some wrong indents, forgotten test logging)

**Comment by asgothian** [comment]
Hmm.. i thought i removed all the forgotten loggings. 
As for the aliveStates - i was not able to pull this information from the object tree from the admin.js without significantly slowing down the setup. It was the last straw, considering that it is just a list of is's, i thought this the lesser of 2 evils

I'll look through the code again.

About stability: i lose connection to the Philips remote as well - it survives to one or two reboots, never more. Motion sensors (Xiaomi) run stable for a few weeks now, same with window sensors.

A

**Comment by asgothian** [comment]
Ok - i found the two console.log i forgot. The rest i saw was in or should stay in.
The function name should be correct now, too.

A.

**Comment by arteck** [comment]
@allofmex any protests ????? or it's ok

**Comment by asgothian** [comment]
Keep it on hold for now - there's something fishy going on. Several people have issues when updating to 10.3. I need to look into that first.

**Comment by allofmex** [comment]
> any protests ?

Didn't tested it yet, still tracing other issues :-/

1. I like the idea to have a card for coordinator too (firmware version,...)
2. Configure: Thought to sniff hue bridge, how bind/config is handled there, but had no time yet. Maybe we can run config-check only on non time-critical incoming message??
3. **Whats the others opinion** on the extra `aliveStates = {},` in admin? It's redundant data in my opinion, we have `available` state in objects already, this would add another aliveStates record on client side. By the way: Network map shows online/offline info already (device red/green)

**Comment by allofmex** [comment]
This was NOT to be merged yet right????

**Comment by kirovilya** [comment]
@allofmex Something is wrong? Need revert?

**Comment by kirovilya** [comment]
I have not tried these changes yet.

**Comment by allofmex** [comment]
1. @asgothian mentioned not to merge because of some problems (Apr. 12) and there are still questions open (my post Apr. 14).
2. It is not fully solving our configureDevice problem yet.

I vote for revert until it is complete.

**Thoughts about a solution**
One partial solution is to trigger configureDevice in `endDeviceAnnce` event instead `newDevice`. It is called earlier, so chance is much higher that device is still alive. In my tests, configure was successful in 99% after `endDeviceAnnce` compared to ~50% with `newDevice`.

Problem is:
Not all devices seem to re-announce themselfes if shepherd/net was restarted. Hue do immediately, Eurotronics did not. Asgothian is right that we need some kind of "configure if device sends a message".
A full solution should include:

- configure all devices on one of there first messages after adapter started (must be open for LONG time, because enddevice may sleep long)

- always re-configure on `endDeviceAnnce` (device may have been reseted)

- ignore devices after some time if they did not send anything within the last 12h(?), assume they are not in net anymore (unplugged...)

I thougth about a last-configured timestamp per device (null at adapterstart. If `null` or `older 24h` -> `configure`)

What is not solved yet: **when** to check if device was configured already. If in onDevEvent, it would slowdown the event processing in case of long to-be-configured lists. But the events should be handled as fast as possible to have fast response between motion-detected and light-on..

Do we have another non-attribute-report device event, that fires frequently or for sure after shepherd restart?

**Comment by kirovilya** [comment]
Ok. Rever from master

**Pull request merged**
