### PR TITLE
Use readAfter states for reading values after main changes

### PR DESCRIPTION
**Pull request by modmax**
Dropped linkedStates from OSRAM devices cause they were causing too much errors.
Instead read command are introduced, which are executed after level has been set to synchronize
state "state" with internal zigbee device state ON or OFF.

### CODE REVIEW

**Comment by modmax** [comment]
Hi Ilya,
I have a strange behaviour now when running the the zigbee adapter with and without queue.
Withe enabled queue the read after states are processed as expected, but when the queue is disabled then there is a ZCL error which I cannot explain. The code for both is the same to process the readAfter states. First thought that i was caused by changed zcp-packet or cc-znp packet .. but the result was the same. I didn't have such issues when I testet id yesterday with changes done on the master branch.
Also the message and payload is correctly build in both cases.

Any idea?

`
-- with queue
2019-01-08 10:42:15.648  - [34mdebug[39m: zigbee.0 publishFromState - readAfter: deviceId=0x8418260000ca7660, message={"cid":"genOnOff","cmd":"read","cmdType":"foundation","zclData":[{"attrId":0}],"cfg":{"manufSpec":0,"disDefaultRsp":0}}
2019-01-08 10:42:15.652  - [34mdebug[39m: zigbee.0 2019-01-08T09:42:15.652Z zigbee:controller debug Zigbee publish to '0x8418260000ca7660', genOnOff - cmd read - payload [{"attrId":0}] - endpoint 3 undefined
2019-01-08 10:42:15.652  - [34mdebug[39m: zigbee.0 Zigbee publish to '0x8418260000ca7660', genOnOff - cmd read - payload [{"attrId":0}] - endpoint 3
2019-01-08 10:42:15.652  - [34mdebug[39m: zigbee.0 2019-01-08T09:42:15.652Z zigbee-shepherd:request REQ --> AF:dataRequest, transId: 9
2019-01-08 10:42:15.653  - [34mdebug[39m: zigbee.0 Tue, 08 Jan 2019 09:42:15 GMT cc-znp:SREQ --> AF:dataRequest, { dstaddr: 13612, destendpoint: 3, srcendpoint: 1, clusterid: 6, transid: 9, options: 48, radius: 30, len: 5, data: <Buffer 00 09 00 00 00> }
2019-01-08 10:42:15.658  - [34mdebug[39m: zigbee.0 Tue, 08 Jan 2019 09:42:15 GMT cc-znp:AREQ <-- AF:dataConfirm, { status: 0, endpoint: 1, transid: 8 }
2019-01-08 10:42:15.658  - [34mdebug[39m: zigbee.0 2019-01-08T09:42:15.658Z zigbee-shepherd:af dispatchIncomingMsg(): type: dataConfirm, msg: [object Object]
2019-01-08 10:42:15.661  - [34mdebug[39m: zigbee.0 2019-01-08T09:42:15.658Z zigbee-shepherd:msgHdlr IND <-- AF:dataConfirm, transId: 8
2019-01-08 10:42:15.672  - [34mdebug[39m: zigbee.0 Tue, 08 Jan 2019 09:42:15 GMT cc-znp:SRSP <-- AF:dataRequest, { status: 0 }
2019-01-08 10:42:15.672  - [34mdebug[39m: zigbee.0 2019-01-08T09:42:15.672Z zigbee-shepherd:request RSP <-- AF:dataRequest, status: 0
2019-01-08 10:42:15.704  - [34mdebug[39m: zigbee.0 Tue, 08 Jan 2019 09:42:15 GMT cc-znp:AREQ <-- AF:incomingMsg, { groupid: 0, clusterid: 8, srcaddr: 13612, srcendpoint: 3, dstendpoint: 1, wasbroadcast: 0, linkquality: 7, securityuse: 0, timestamp: 3117816, transseqnumber: 0, len: 31, data: <Buffer 18 08 01 00 00 00 20 4c 01 00 00 21 00 00 10 00 00 21 00 00 11 00 00 20 ff 12 00 00 21 00 00> }
2019-01-08 10:42:15.704  - [34mdebug[39m: zigbee.0 2019-01-08T09:42:15.704Z zigbee-shepherd:af dispatchIncomingMsg(): type: incomingMsg, msg: [object Object]
2019-01-08 10:42:15.709  - [34mdebug[39m: zigbee.0 2019-01-08T09:42:15.709Z zigbee-shepherd:msgHdlr IND <-- AF:incomingMsg, transId: 0
2019-01-08 10:42:15.710  - [34mdebug[39m: zigbee.0 2019-01-08T09:42:15.710Z zigbee:controller event msg { groupid: 0,  clusterid: 8,  srcaddr: 13612,  srcendpoint: 3,  dstendpoint: 1,  wasbroadcast: 0,  linkquality: 7,  securityuse: 0,  timestamp: 3117816,  transseqnumber: 0,  len: 31,  data:    { '0': 24,     '1': 8,     '2': 1,     '3': 0,     '4': 0,     '5': 0,     '6': 32,     '7': 76,     '8': 1,     '9': 0,     '10': 0,     '11': 33,     '12': 0,     '13': 0,     '14': 16,     '15': 0,     '16': 0,     '17': 33,     '18': 0,     '19': 0,     '20': 17,     '21': 0,     '22': 0,     '23': 32,     '24': 255,     '25': 18,     '26': 0,     '27': 0,     '28': 33,     '29': 0,     '30': 0 },  zclMsg:    { frameCntl: { frameType: 0, manufSpec: 0, direction: 1, disDefaultRsp: 1 },     manufCode: 0,     seqNum: 8,     cmdId: 'readRsp',     payload: [ [Object], [Object], [Object], [Object], [Object] ] } } { modelId: 'Classic A60 RGBW' }


-- without queue
2019-01-08 10:44:09.968  - [34mdebug[39m: zigbee.0 publishFromState - readAfter: deviceId=0x8418260000ca7660, message={"cid":"genOnOff","cmd":"read","cmdType":"foundation","zclData":[{"attrId":0}],"cfg":{"manufSpec":0,"disDefaultRsp":0}}
2019-01-08 10:44:09.979  - [34mdebug[39m: zigbee.0 2019-01-08T09:44:09.979Z zigbee:controller debug Zigbee publish to '0x8418260000ca7660', genOnOff - cmd read - payload [{"attrId":0}] - endpoint 3 undefined
2019-01-08 10:44:09.979  - [34mdebug[39m: zigbee.0 Zigbee publish to '0x8418260000ca7660', genOnOff - cmd read - payload [{"attrId":0}] - endpoint 3
2019-01-08 10:44:09.981  - [34mdebug[39m: zigbee.0 Error: Payload of commnad: read must have attrId property.    at /work/iobroker/node_modules/zcl-packet/lib/foundation.js:176:27    at Array.forEach (<anonymous>)    at FoundPayload._getBuf (/work/iobroker/node_modules/zcl-packet/lib/foundation.js:171:25)    at /work/iobroker/node_modules/zcl-packet/lib/foundation.js:112:22    at Array.forEach (<anonymous>)    at FoundPayload.frame (/work/iobroker/node_modules/zcl-packet/lib/foundation.js:111:21)    at Object.zcl.frame (/work/iobroker/node_modules/zcl-packet/lib/zcl.js:66:78)    at Object.af.zclFoundation (/work/iobroker/node_modules/zigbee-shepherd/lib/components/af.js:263:25)    at ZShepherd._foundation (/work/iobroker/node_modules/zigbee-shepherd/lib/shepherd.js:664:20)    at Endpoint.ep.foundation (/work/iobroker/node_modules/zigbee-shepherd/lib/shepherd.js:552:25)
2019-01-08 10:44:09.981  - [31merror[39m: zigbee.0 uncaught exception: Payload of commnad: read must have attrId property.
2019-01-08 10:44:09.982  - [31merror[39m: zigbee.0 Error: Payload of commnad: read must have attrId property.
    at /work/iobroker/node_modules/zcl-packet/lib/foundation.js:176:27
    at Array.forEach (<anonymous>)
    at FoundPayload._getBuf (/work/iobroker/node_modules/zcl-packet/lib/foundation.js:171:25)
    at /work/iobroker/node_modules/zcl-packet/lib/foundation.js:112:22
    at Array.forEach (<anonymous>)
    at FoundPayload.frame (/work/iobroker/node_modules/zcl-packet/lib/foundation.js:111:21)
    at Object.zcl.frame (/work/iobroker/node_modules/zcl-packet/lib/zcl.js:66:78)
    at Object.af.zclFoundation (/work/iobroker/node_modules/zigbee-shepherd/lib/components/af.js:263:25)
    at ZShepherd._foundation (/work/iobroker/node_modules/zigbee-shepherd/lib/shepherd.js:664:20)
    at Endpoint.ep.foundation (/work/iobroker/node_modules/zigbee-shepherd/lib/shepherd.js:552:25)
`

**Comment by modmax** [comment]
According to the error:
That errors just occurs when the queue is disabled; so I catch that expetion and log it; but that's not the desired behaviour. I furthermore think, that's a bug in zigbee-sheperd or zcl-packet.
It seams that it just works correctly if a write is done before read ... but I'm not able to find the reason for it.

The same code with enabled queue works as excpected.

**Comment by modmax** [comment]
Okay ... error found ... Reason was an incorrect setting of the zclData (packed into an array) on publishDisabledQueue function; that leads to an array for zclData instead of the expected object.

**Comment by kirovilya** [comment]
Hello, Markus. I seen your letter. But was busy...
I am currently working on zigby groups (a **groups** branch), they must solve some of the problems with mass sending messages.
It is good that you were able to solve problems with devices! Finally, someone else began to understand this topic! I am glad!

**Comment by kirovilya** [comment]
Can you check your code version with using transition_time state? For example set it to 5 or 10 seconds

**Comment by modmax** [comment]
I'me using a transition time of 5 for the lamps and it works; that works.
Perhaps the read after states should be placed in the read of the brightness state, when a queue is used;
so that first the read of brightness is done and afterwards the read of the readAfter states.

The only thing that i cannot handle is that OSRAM plugs are ending events of brightness changes even befpr the transition time is over. Then you see a "remainingTime" in the event. But sometimes the remainingTime is not in the event data. Then it's just set in the endpint list, where the whole state of the map is returned. 
Therefore I skipped events with a remainingTime ... but sometimes it's not there.

Also the OSRAM lights cannot handle to much Zigbee requests withe the Zigbee stick. Especially if you use VIS with some sliders or the fantastic color picker, then the requests are too much and a 205-Error occures. After 30 seconds the lamps works again; cause then all peding zigbee pushlish message has been timed out and new events could be send.

I've just tested the changes with an OSRAM RGBW lamp and a RGBW flex; the other lamps are connected to a hue bridge. And with the hue bridge there are no problems and all is working without any problems. May be because of better hardware, or using the ZLL or anything else .. who knows.

**Pull request merged**
