### PR TITLE
Added Gledopto Wall switch

### PR DESCRIPTION
**Pull request by frankjoke**
Got nice wall switch from Gledopto and integrated it.

### CODE REVIEW

**Comment by Sacred-Shadow** [comment]
Don't you have a picture of that thing?
At least there is no picture in your request?

**Comment by frankjoke** [comment]
I just re-used another wall swith photo
Gledopto-GL-W
THe only photo I have is not so nice...

**Comment by Sacred-Shadow** [comment]
Hab online eines gefunden. 
image

Müsste nur auf die richtige Größe gebracht werden.

**Comment by kirovilya** [comment]
thank you

**Pull request merged**
