### PR TITLE
Hue White and color ambiance Play Lightbar and others

### PR DESCRIPTION
**Pull request by arteck**

### CODE REVIEW

**Comment by Apollon77** [comment]
This is currently not working for me!!
Is the "arteck" version of the sheppard lib intended?

**Comment by arteck** [comment]
check now

**Comment by arteck** [comment]
new version of zigbee-shepherd-converters is buggy

**Comment by Apollon77** [comment]
So should I retest or ot?

**Comment by Apollon77** [comment]
@arteck tested again, LCT024 is shown correct in UI, but listed as "unknown" on start and error "Unknwon device model LCT024" when I try to control it

**Pull request closed without merging**
