### PR TITLE
Update Innr SP 120 to support Plug Voltage

### PR DESCRIPTION
**Pull request by derlucas**
adding states.plug_voltage to the Innr SP120 Device
maybe it can be enabled for the other SP XXX Devices too, but i don't have them, i can not check.

### CODE REVIEW

**Comment by asgothian** [comment]
Please verify if the affected innr plug will generate the desired state if added to the exclude list
If this is the case, please use the herdsman exposed states you get from using the device through the exclude list rather than the explicitly defined states from the devices.js (i.e. keep the device type in the exclude list)

**Comment by derlucas** [comment]
Thanks for your reply. I unfortunately have no clue what herdsman is and where i should edit something.

**Comment by asgothian** [comment]
The Zigbee Adapter has a configuration option called "Exclude List" or "Ausschlussliste". Adding a device to this list bypasses the definitions in the devices.js file and instead generates states based on information gained from the zigbee-herdsman-converters, which is responsible for the communication between the zigbee Adapter and the actual Hardware.

A.

**Review by asgothian — CHANGES_REQUESTED** [review]
Please test if the states generated with the line 1621 removed are identical in function to the ones generated with 1621 in place. 

If this is the case, please remove line 1621 entirely to move towards using herdsman exposes as the main method of generating states for ioBroker.

**Comment by arteck** [comment]
close here

**Pull request closed without merging**
