### PR TITLE
Map enhanced fix

### PR DESCRIPTION
**Pull request by allofmex**
Fixed node selection (note: attributes must be set initially to 'unselected' color,.. values), real values are set in `chosen:{...}`

Also added some other small fixes

### CODE REVIEW

**Comment by kirovilya** [comment]
why you need to select node? let it show all information immediately

**Comment by kirovilya** [comment]
so I wanted to see what your map would look like.

**Comment by allofmex** [comment]
map_messy
Please not! Thats just 18 devices....

**Comment by kirovilya** [comment]
> Please not! Thats just 18 devices....

hmmm. ok. now undestand :)

**Comment by allofmex** [comment]
:-) 
(I still prefer the smaller arrows, but up to you)

**Comment by kirovilya** [comment]
And how now showing?

**Comment by kirovilya** [comment]
Can make a checkbox on the map: "old view" or "new view"?

**Comment by kirovilya** [comment]
"old view" - like in 0.9.2 version, without multilines :)

**Comment by allofmex** [comment]
map_clean

**Comment by kirovilya** [comment]
good. but 'red' lines not seen

**Comment by allofmex** [comment]
Checkbox is possible, of course. 
But not sure what your goal is:
Old view has limitation. The single-lines shows only one information:
- (line visible) - device has at least one route link 
- (no line) - device has no route
- the line is chosen randomly (it may show a weak link even that a stronger exists)

To have a single-link view it would be needed to filter the lqi routing data first. (and show only the strongest link)

**Comment by kirovilya** [comment]
goal is:
* in the majority of cases, the previous simplified representation was convenient, since made it clear there is a connection or not. and if the device was connected via a router, it was visible.
* the updated view is confusing, but reveals the complexity of the network structure and shows different signal levels.

ok, let's leave for now your new presentation.

**Comment by nob0dy80** [comment]
@allofmex 
this is an AMAZING feature! This has to be implemented with optional checkbox for sure.
Since many people have problems with the adapter (or the firmware, the issue isnt very clear till now) i could use this feature to analyse the connections.
Seems like i'm very close to find out why CC2530 and CC2531 randomly freezes at so many users.

**Comment by allofmex** [comment]
>  simplified representation ... made it clear there is a connection or not.
Ok, lets have both. I'll update with a selector.

**Comment by nob0dy80** [comment]
@allofmex @kirovilya 
just updated and the map isnt useable any longer for me.
routers and sensors jumping arround so fast, you cant even read their names. is that expected behavior?

See: https://youtu.be/rnY7vo7Gxd8

**Comment by kirovilya** [comment]
@nob0dy80 nice view... :( I wanted to leave the "physics" for beauty in a simplified representation.

**Comment by allofmex** [comment]
Yes, physics most be false, no other chance for larger nets.
I had the same problem

**Comment by kirovilya** [comment]
here map is silent http://visjs.org/examples/network/exampleApplications/lesMiserables.html

**Comment by nob0dy80** [comment]
@kirovilya  @allofmex 
yeah ..thats the party-mode :-)

is there any way to turn physics off for now (the checkbox doesnt seem to be included yet)?
i really love this idea and feature, but in this way its not useable for now.

**Comment by kirovilya** [comment]
@nob0dy80 https://github.com/ioBroker/ioBroker.zigbee/blob/master/admin/admin.js#L622

**Comment by nob0dy80** [comment]
thanks

**Comment by nob0dy80** [comment]
@kirovilya 
can the drawing lines to all routers also be disabled with a false flag ?
seems like you were right for now, i cant read anything on the map cause of so many lines.. moving or not.. 
i guess its really enough to see the active route :-|

**Comment by allofmex** [comment]
Currently working on it...

**Comment by nob0dy80** [comment]
@allofmex 
you're my man .. did you took a look at my datapoint thoughts regarding the configuration issue of switches ?

**Comment by allofmex** [comment]
How about this:
map3

This may be the default view. Now it shows the real (current) parents.
I don't want to have "Previous Parents" selected by default because many devices have multiple previous links, it would look messy again. Means: "All fine except a device label is red" (bottom right).

**Comment by allofmex** [comment]
@kirovilya
Physics are enabled on parent/child links (only). That way it seems to work :-)

**Comment by Thomas1305** [comment]
How can i get this feature?
Just Install the adapter from GitHub?

**Comment by kirovilya** [comment]
@allofmex Are there too many checkboxes? :) 
let's try. do PR

**Comment by nob0dy80** [comment]
@allofmex 
this is looking great, but you really should bring back the link quality to the lines.

**Comment by allofmex** [comment]
@nob0dy80 
The link quality becomes visible if a device is clicked. 

@Thomas1305 
It needs to be merged first. Then you may install from Github.

**Comment by nob0dy80** [comment]
@allofmex 
do you think this is a good idea for the defaul map view ? i think it really would be better to display them all like before to have quick overview. Or maype as an additional checkbox?!?

**Comment by allofmex** [comment]
> i think it really would be better to display them all like before

If a link is weak (<10), the line will be red, else its blue. Doesn't really matter if a good link is 20 or 120, right?
It's possible with another checkbox, but not sure if needed.

**Comment by nob0dy80** [comment]
@allofmex 
yeah i'm with you ... 
this sounds very good. are there only that two colors ? Maybe its possible to display the signal strength in an other way?! From dark blue to lighter blue or something like that.
i'm afraid of loosing the "overview".

**Comment by kirovilya** [comment]
Checkout current repo - I added view config button on map

**Comment by allofmex** [comment]
Looks fine for me. May help especially on small screens. Thanks

**Pull request merged**
