### PR TITLE
Networkmap enhanced

### PR DESCRIPTION
**Pull request by allofmex**
While tracing some weak network link issues, I noticed that current NetworkMap has some limitations:
It shows only a (random) single link per device. (This link has not necessarily the stronges or weakest link quality) 
Here a try to enhance:
netmap

Looks a bit chaotic at first so here some details:

- Select a device to see all its links highlighted
- Link quality is shown **bidirectional** (routers only)
- Low link-quality links are marked red (note bulb at lower left, weak link only in one direction!)
- lqi "offline" status added
- full mesh structure visible (may help to find best spot to place a router acting as repeater)

### CODE REVIEW

**Comment by kirovilya** [comment]
It looks cool, but too cluttered. Let's try. Let's see what the users say.

**Comment by allofmex** [comment]
Thanks.

> It looks cool, but too cluttered. 

I agree. Maybe we will have a better idea or options in future.

Tried vis.js hierarchical layout, but looks worse. We should implement some device filter options (show "only router",...) in future. But requires some more coding.

**Comment by kirovilya** [comment]
Hi, allofmex
Can you check out last code for network map with your devices? and show picture

**Comment by allofmex** [comment]
I see what you mean, PR following. Good idea to have the link quality as multi line...

**Comment by nob0dy80** [comment]
@allofmex 
missed the last time.
is there any enhance when i pull the latest from git ? is there an better overview ?

**Comment by allofmex** [comment]
Last state is this https://github.com/ioBroker/ioBroker.zigbee/pull/248#issuecomment-473944303
Except that the check boxes were moved to a sub menu

**Pull request merged**
