### PR TITLE
Eurotronic final

### PR DESCRIPTION
**Pull request by asgothian**
Finalized eurotronic support
added bitron 902010/25 
fixed osram B40 DIM Z3 - lamp does not support CT

Note: against the previous commit, i have split hvacThermostat_pi_heating_demand and SPBZ0001_auto_valve_position, despite both accessing the same datapoint. This is intentional, as the hvacThermostat standard does not clearly define pi_heating_demand as a valve position. This is specific to radiator thermostats.

### CODE REVIEW

**Comment by kirovilya** [comment]
Thank you!

**Comment by allofmex** [comment]
@asgothian: thanks for the update on pi_heating_demand, sounds reasonable. 
Looks like Eurotronic support is fine now.
What we still may add is thermostat_setpoint_raise_lower (relative change of target temp, "+/- x degree"). But not urgent, same effect can be achieved by what we have already.

**Comment by allofmex** [comment]
@asgothian: I was wrong:
```
states.hvacThermostat_unoccupied_heating_setpoint,
states.hvacThermostat_occupied_heating_setpoint,
states.hvacThermostat_system_mode, 
```
got lost in in last PR! May you add this again?

**Comment by asgothian** [comment]
unoccupied and occupied heating set point got lost, as the thermostat does not actually seem to support them. There is no way to set occupancy status, and the values set will always be copied to heating_setpoint.

error status message was removed in order to not have to adapt in case of firmware upgrades which introduce more error states, while the system_mode has been renamed to trv_mode

These changes were intentional, i would rather not set them back in.

**Comment by allofmex** [comment]
Understand your points.

> the values set will always be copied to heating_setpoint

I suggest to add (un)occupiedHeatingSetPoints anyways out of following reason:
First, it is the standard way to address a valve.
Second, it provides a way to differ between changes from zigbee and changes by user (button on device).
**Example:**

1. Script always writes to (un)occupied setpoint -> _current_heating_setpoint copied by device_
2. temp got changed on device by button -> _only current_heating_setpoint changes_

In both cases our on(current_heating_setpoint) event fires, but we just need to check if (un)occupied setpoint has changed too to know, where the change came from. And original value is not lost but still in (un)occupied.
(Lets just let the user decide, if and how he want to handle it. It does not hurt to have them all, maybe we find the way how occupancy is handled.)

> system_mode has been renamed to trv_mode

SPBZ0001_system_mode, SPBZ0001_trv_mode and hva system_mode are **not the same**:
```
success {"msg":[{"attrId":28,"status":0,"dataType":48,"attrData":4}]}
success {"msg":[{"attrId":16384,"status":0,"dataType":48,"attrData":2}]}
success {"msg":[{"attrId":16392,"status":0,"dataType":34,"attrData":1}]}
```
**Standard hva system_mode should be added!**

> error status message was removed

Hm, technically correct. Up to you. But that's actually what frustrates me most on all this smarthome stuff, most of the time you spent is wasted by browsing the web to find out how value are to be interpreted... IMHO 
(OK, Error E1, Unknown Code 128 is simple and still firmware update save)

**Pull request merged**
