### PR TITLE
Added Iluminize 5120.1100

### PR DESCRIPTION
**Pull request by Sacred-Shadow**
Iluminize has reissued its dimming actuator.
Technically & the product name is the same as the model 511.201.

Tested and working. (on/off & brightness)

Pull to converter already done.
https://github.com/Koenkk/zigbee-herdsman-converters/pull/2172

### CODE REVIEW

**Comment by asgothian** [comment]
Can you please test if the device works based solely on the exposes offered by the zigbee-herdsman-converters ? The test can be done by removing the entry in the devices.js.

If it is working with exposes, 3 options exist:
- rely fully on exposes, i.e. leave the device out from the devices.js
- rely on exposes for function, but keep the image, i.e. remove the states and linkedstates properties.
- do a full integration and leave the changes as is.

**Comment by Sacred-Shadow** [comment]
I don't know what you're getting at.
We have adapted the converter (https://github.com/Koenkk/zigbee-herdsman-converters/pull/2172) and the changes in this pull.

Then we could connect the dimmer.
The values ​​are all there and the controls work. On / off works and so does the brightness.

image

**Comment by asgothian** [comment]
With the new function "exposes" in the zigbee-herdsman-converters, devices should work with the iobroker.zigbee as soon as the herdsman with the device definition is being used.

It should no longer be needed to explicitly implement the same device in the iobroker adapter. This is a major improvement, but we need to test this feature to ensure that the provided exposes are working for us. Hence the request to test if the device works even without your changes in the iobroker.zigbee;s devices.js.

A.

**Comment by Sacred-Shadow** [comment]
Thank you for the explanation.

I asked that the device is now permanently installed and the ceiling is closed.
The colleague doesn't feel like opening the blanket again for the test.

Everything is already working for him.

**Comment by asgothian** [comment]
The Test would be purely on the Software side - no new pairing needed. Please check if a device works with exposes before changing the devices.is in the future.

**Pull request merged**
