### PR TITLE
ignore state mapping errors

### PR DESCRIPTION
**Pull request by Zefau**
added configuration option to ignore state mapping errors for specified devices

### CODE REVIEW

**Comment by kirovilya** [comment]
I don’t understand why such a revision? if the device does not have a description (statesmap), then how to work with it?

**Comment by Zefau** [comment]
I have the device added in my Zigbee adapter and I keep getting these errors (in very small intervals).

If I delete the device, the actual physical bulb blinks when turning it on via physical switch (I guess because it is not assigned anywhere). This is why I had to add it again in the Zigbee adapter.

If I browse through the Issue I see a lot of those saying `Device ... not described in statesMapping` (like mine https://github.com/ioBroker/ioBroker.zigbee/issues/1248).
For those users this would be an option to keep the device in the adapter and avoid the errors in the log.

**Comment by arteck** [comment]
I don’t understand  you problem also....

sollen wir das mal im Discord bequatchen?? vielleicht verstehe ich dein Problem besser ..

**Comment by asgothian** [comment]
This can be related to issue #1219.
In general: Handling of undefined devices is currently inconsistent. I have seen cases where devices will generate up to 60 mapping state error messages during pairing before being successfully paired. This is linked to the extended use of exposes where a device is added to the states mapping only after having been completely paired.

@Zefau 's original issue would be fixed by ensuring that the bulb in question is supported by the zigbee-herdsman-converters.

I would propose a different change than presented here:
- generate a state under zigbee.info to record all devices unmapped devices
- clear this state at adapter start
- when a message from an unmapped device is seen - check against this state. 
- For devices already recorded in this state - mute the warn message.
- For devices which are not recorded in this state - print the warn message, add device to this state.

This would serve both requirements. The operator would gain a simple means to verify that no unmapped devices are part of their network and the adapter would stop spamming the log with essentially repeat messages.

Thoughts ?

A

**Comment by asgothian** [comment]
Closing this - an alternative means of dealing with these messages has been integrated into the adapter.

**Pull request closed without merging**
