### PR TITLE
Update devices.js

### PR DESCRIPTION
**Pull request by modmax**
Fixed states for HGZB-41 and removed duplicate entry.

### CODE REVIEW

**Review by asgothian — CHANGES_REQUESTED** [review]
Can you check if the devices will work as before (with identical states) if the new line 2327 is removed and the device is run solely through the herdsman exposes with identical state names in states tree ?

If this test is successful (functionality is retained, state names are identical) i would propose to remove said line permanently in order to slowly shift towards exposes as our main state defining method.

**Comment by modmax** [comment]
@asgothian 
I removed the line 2327 from the devices.js. But I cannot exclude that model in the exclude list. All other zigbee devices can be excluded, but not this one.

The  zigbee-herdsman-converters declaration is:
`
zigbeeModel: ['FNB56-ZSW01LX2.0'],
model: 'HGZB-42-UK / HGZB-41 / HGZB-41-UK',
description: 'Smart switch 1 or 2 gang',
vendor: 'Nue / 3A',
extend: extend.switch(),
`
So there are no exposes, which could be used; and so no exclusion on the exclusions page can be done.

The problem ist that there are 3 states: brightness, brightness_move and effect, which cannot be used cause unsupported; if something is changed in there, then just the unsupported message is shown in the log and the values stay red (indicating a problem setting this value).

**Comment by asgothian** [comment]
> @asgothian
> I removed the line 2327 from the devices.js. But I cannot exclude that model in the exclude list. All other zigbee devices can be excluded, but not this one.
> 
> The zigbee-herdsman-converters declaration is:
> `zigbeeModel: ['FNB56-ZSW01LX2.0'], model: 'HGZB-42-UK / HGZB-41 / HGZB-41-UK', description: 'Smart switch 1 or 2 gang', vendor: 'Nue / 3A', extend: extend.switch(),`
> So there are no exposes, which could be used; and so no exclusion on the exclusions page can be done.
> 
> The problem ist that there are 3 states: brightness, brightness_move and effect, which cannot be used cause unsupported; if something is changed in there, then just the unsupported message is shown in the log and the values stay red (indicating a problem setting this value).

Once you remove the states definitions the device is already using the exposes and can no longer be entered into the exclude list. This is ok.
Can you post the log line you get when trying to change the value ?

As far as there not being any exposes - this is not correct. The `extend: extend.switch()` references to a default which includes both exposes and state definitions. Also - after starting the adapter with the removed "states" can you use the "state cleanup" function to remove unlinked states (or alternatively delete the NUE states and then restart the adapter) so that you only see the states generated by the exposes (which really should be just one)

A.

**Comment by modmax** [comment]
@asgothian 
1.) If the states is contained in devices.js then there is just the state 'state'. Also I cannot add this model in the exclusion list on exlusion tab, cause it's not selectable.
2.) After removing line 2327 and restarting the zigbee adater the states "brightness", "brightness_move" and "effect" are present.
I don't know from where these states are coming excactly.
3.) When seeting i.e. 50 in the brightness the value stays red and the log says:
`2021-06-20 10:36:21.472 - error: zigbee.0 (27529) No converter available for 'HGZB-42-UK / HGZB-41 / HGZB-41-UK' with key 'brightness' `
Same for effect and brightness_move.

**Comment by asgothian** [comment]
> @asgothian
> 1.) If the states is contained in devices.js then there is just the state 'state'. Also I cannot add this model in the exclusion list on exlusion tab, cause it's not selectable.
> 2.) After removing line 2327 and restarting the zigbee adater the states "brightness", "brightness_move" and "effect" are present.
> I don't know from where these states are coming excactly.
> 3.) When seeting i.e. 50 in the brightness the value stays red and the log says:
> `2021-06-20 10:36:21.472 - error: zigbee.0 (27529) No converter available for 'HGZB-42-UK / HGZB-41 / HGZB-41-UK' with key 'brightness' `
> Same for effect and brightness_move.

This is an indication for a wrong expose from the herdsman. It is good to know that they are exposed wrongly. As this will cause issues if we activate that in the zigbee adapter right now, i've pushed the PR through in its original form.

Thank you for performing the tests and identifying a future issue.

A.

**Pull request merged**
