### PR TITLE
img update

### PR DESCRIPTION
**Pull request by arteck**

### CODE REVIEW

**Comment by kirovilya** [comment]
I think you need to remove the shadows or find another picture without shadows

**Comment by kirovilya** [comment]
:)
Your image with shadow:
image

Here without shadow https://images-na.ssl-images-amazon.com/images/I/51uZzYJr9AL._SL1200_.jpg

**Comment by arteck** [comment]
better :-)

**Comment by arteck** [comment]
new osram bulb

**Comment by kirovilya** [comment]
Merged to dev branch

**Pull request merged**
