### PR TITLE
Groups

### PR DESCRIPTION
**Pull request by asgothian**
Rewrite of groups functionality
- removed crashes when manipulating groups
- removed orphaned code which referenced the zigbee-shepherd
- autodetect groups present in the database (can be deleted or named and used)
- Update states for grouped devices if the group state is changed.
- smooth dimming for groups and lights which do not use exposes
- ACK set for successful changes
- Error message for unsupported changes
- Stop trying to add/remove a device to groups at the first error.
- Error message in Config when an action fails
- Update the device tile when groups are modified

Known effects:
- successful ack for the group state relies on ALL group members responding to the read request of the specific members states. This does NOT currently work for the "color" state.
- Color state does not support reading and will not be updated on the group members.
- wrong colortemp values entered for the group will not be corrected on the group, even if the group members report correct values to the members.
- Brightness changes with TransitionTime > 0 will result in a wrong brightness value listed for all group members as the read request is sent immediately, i.e. before the transition time is complete.
- Due to limitations in the zigbee-herdsman, changing any group entries on a device is performed by removing the device from all current groups and then adding it back to all new groups. Therefore, the error message presented to the user when a device cannot be reached may be about being unable to remove the device from all groups.

### CODE REVIEW

**Comment by asgothian** [comment]
This PR should at least partially fix the issues #831 and #970

**Comment by kirovilya** [comment]
can merge?

**Comment by asgothian** [comment]
Yes please.

**Comment by kirovilya** [comment]
I propose to release version 1.5 after merging my changes with the dashboard

**Pull request merged**
