### PR TITLE
support for Danalock V3

### PR DESCRIPTION
**Pull request by stream2me**
added support for Danalock v3:
- new device V3-BTZB
- new state: lock_state

working so far:
- battery percentage
- battery low state
- lock/unlock the lock by manually changing the value in lockState

not working:
 status update after the lock was moved by hand or by the app.

### CODE REVIEW

**Comment by buggyracer79** [comment]
Mmmmh received my Danalock V3 BTZB today. Can't connect...... io just doesn't find it. Any ideas?

In the App under "Smarthome" it shows Z-Wave, on the Label ZigBee. I tried connect it to my Zwave device, same ending..... So not sure, what is wrong

**Comment by buggyracer79** [comment]
Ah, I guess I have to update something manually.... Any step by step help or something? Or is ist coming soon with a regular update?

**Comment by stream2me** [comment]
First you have to setup your lock using the app.
You need to update the zigbee-shepherd-converter. See this [PR](https://github.com/Koenkk/zigbee-shepherd-converters/pull/407).The latest release should be fine.
Finally you have to exchange the devstate.js with the one including the commit.

**Comment by buggyracer79** [comment]
Hi, thanks for responding, but I have no idea how to do that.... Mmmh. Are
there any tutorials?

stream2me <notifications@github.com> schrieb am Fr., 17. Mai 2019, 12:12:

**Pull request merged**
