### PR TITLE
Binding

### PR DESCRIPTION
**Pull request by kirovilya**

### CODE REVIEW

**Comment by SchumyHao** [comment]
Binding means device can control each others without ioBroker?
Or can control each others without coordinator?

**Comment by kirovilya** [comment]
without iobroker and coordinator. but not all devices can do that

**Comment by SchumyHao** [comment]
Must support zigbee3.0? like touchlink?

**Comment by kirovilya** [comment]
not only zigbee 3.0 - z-stack 1.2 support too. it is common zigbee feature.
yes, it is like touchlink.
For expample I can bind Aqara Opple button to concrete relay or bulb, or group. And it will be work without coordinator.
But currently work is not complited... have no time :(

**Comment by SchumyHao** [comment]
OK thank you for your info.

I can take a look this code

**Pull request merged**
