### PR TITLE
Fixes #218

### LINKED ISSUE #218: Actual zigbee shepherd converters leads to always setting brightness to zero
The zigbee shepherd converters has changed:
https://github.com/Koenkk/zigbee-shepherd-converters/blob/6cfafa33fb37dac2ab5f51031b7277b516b6b45c/converters/toZigbee.js#L186
Naughty change to split up "moveToLevel" and "moveToLevelWithOnOff" ...

This leads to always setting brightness to zero if state or brightness is triggered;
cause the message (which are the preparedOptions) in iobroker.zigbee adapter
wiill be parsed for state and brightness also. Right now the transitions is set by the adapter.

To solve this, also the brightness should be set in preparedOptions, if the 
brightness shopuld be changed.

### PR DESCRIPTION
**Pull request by modmax**
brightness will be set in prepared options

### CODE REVIEW

**Comment by modmax** [comment]
Closed, cause contained in pull request #224 from arteck.

**Comment by arteck** [comment]
brightness with state dosnt work 

state = false = brightness = 0
state = true = brightness = 0 <- this is wrong

**Comment by modmax** [comment]
Hi arteck,
what is the exact problem? State will be set as always ... the problem just was that brightness was set to 0, cause not set in prepared options.

**Comment by modmax** [comment]
@arteck 
You we're right ... the brightness worked with that fix, but nor the state.

The reason ist, that the zigbee-shepered-converters use the same functionality for state and brightness.
If state is not set in prepared options, then brighness will be used. 
This leads to the fact, that also when switching the state the states must be set in prepared options, so that the shepherd-converters creates the correct zcl data object.

Hav fixed it with PR #243

**Pull request closed without merging**
